---
name: '⬆️ PortalBrasil - Requisitar acesso'
description: 'Requisita acesso de escrita aos nossos repositórios'
title: "[Acesso]: "
labels: ['Acesso']
projects:
  - portal-br/3
type: Task
body:
  - type: markdown
    attributes:
      value: |
        Considere que você não precisa ter acesso de escrita aos repositórios do PortalBrasil para criar um "pull request", relatar um problema, ou fazer perguntas.

  - type: checkboxes
    attributes:
      label: Código de conduta
      options:
        - label: Eu seguirei o [código de conduta da comunidade Plone](https://plone.org/foundation/about/materials/foundation-resolutions/code-of-conduct)
          required: true

  - type: checkboxes
    id: distribuicoes
    attributes:
      label: Distribuições que eu pretendo auxiliar
      options:
        - label: "Portal Modelo"
        - label: "PortalBrasil: Intranet"
        - label: "PortalBrasil: Comunidade"
        - label: "PortalBrasil: Educação"

  - type: textarea
    id: motivacao
    attributes:
      label: Minha motivação
      description: Nos conte a sua motivação em fazer parte desta comunidade.
      placeholder: "Gostaria de colaborar com código"
    validations:
      required: true
